install: true
before_script:
  - bundle install
  - bundle exec xcake make
  - mkdir -p ~/.cocoapods/repos/ || true
  - bundle exec pod install --verbose --repo-update

script:
  - xcodebuild -workspace DemoPodHeaderSearchPaths.xcworkspace -scheme DemoPodHeaderSearchPaths -sdk iphonesimulator | xcpretty

matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode10.1
